
trigger:
- devel

jobs:
- job: 'SireOSX'
  pool:
    vmImage: 'macOS-10.14'

  timeoutInMinutes: 180

  steps:
  - script: |
      ./compile_sire.sh --install $HOME/sire.app
    displayName: 'Build Sire'
  - script: |
      # create the binary package before running tests, as the package must be clean
      $HOME/sire.app/bin/conda uninstall --yes cmake make clang_osx-64 clangxx_osx-64 llvm
      $HOME/sire.app/bin/conda clean -tipy
      $HOME/sire.app/bin/package_sire > package.log 2>&1
    env:
      SIRE_RUN_FILE: $HOME/sire_devel_latest_osx.run
    displayName: 'Package Sire into a binary'
  - script: |
      #Â run the tests
      $HOME/sire.app/bin/sire_test
    displayName: 'Run Sire tests'
  - script: |
      # deploy the binary to an object store bucket identified by 'par_url'
      $HOME/sire.app/bin/conda install -y pycurl conda-build=3.17 anaconda-client
      $HOME/sire.app/bin/python docker/sire-deploy-devel/deploy.py $HOME/sire_devel_latest_osx.run
      bash docker/sire-deploy-devel/deploy_release.sh
    env:
      PAR_URL: $(parURL)
    displayName: 'Deploy binary to siremol.org'
  - script: |
      # finally create the Sire Conda package and upload to the Anaconda Cloud.
      bash docker/sire-conda/create_package_file.sh
      $HOME/sire.app/bin/python docker/sire-conda/deploy.py $HOME/sire_conda_latest_osx.tar.bz2
      bash docker/sire-conda/update_recipe.sh
      bash docker/sire-conda/build_and_deploy.sh
    env:
      ANACONDA_TOKEN: $(anacondaToken)
      PAR_URL: $(parURL)
    displayName: 'Create Conda package and upload to the Anaconda Cloud'
